language: android
jdk: oraclejdk8
env:
android:
  components:
  - tools
  - build-tools-25.0.0
  - android-25
  - platform-tools
before_install:
  - chmod +x gradlew
script:
  - ./gradlew assembleRelease
